import About from '@/components/home/About'
import Attire from '@/components/home/Attire'
import Banner from '@/components/home/Banner'
import Features from '@/components/home/Features'
import Footer from '@/components/home/Footer'
import News from '@/components/home/News'
import Schedule from '@/components/home/Schedule'
import Scrolltop from '@/components/home/Scrolltop'
import Testimonial from '@/components/home/Testimonial'
import Trainer from '@/components/home/Trainer'
import Head from 'next/head'


export default function Index() {
  return (
    <>
      <Head>
        <title>Orca</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Banner />
      <About />
      <Attire />
      <Trainer />
      <Schedule />
      <Features />
      <Testimonial />
      <Scrolltop />
      <News />
      <Footer />
    </>
  )
}
